version: "3"
services:
  ejabberd:
    image: rroemhild/ejabberd
    container_name: ejabberd
    user: root
    restart: always
#    network_mode: host
    ports:
      - 5222:5222
      - 5269:5269
      - 5280:5280
      - 5277:5277
      - 5443:5443
    volumes:
      - ./ejabberd/database/:/opt/ejabberd/database
      - ./ejabberd/conf/:/opt/ejabberd/conf
      - ./ejabberd/ssl/:/opt/ejabberd/ssl
      - ./ejabberd/upload/:/opt/ejabberd/upload/

    environment:
#       - ERLANG_NODE=localhost
       - XMPP_DOMAIN=it-top.pp.ua
       - EJABBERD_ADMINS=admin@it-top.pp.ua
       - EJABBERD_USERS=admin@it-top.pp.ua:123456
       - EJABBERD_REGISTER_ADMIN_ONLY: true