version: "3"
services:
  ejabberd:
    image: rroemhild/ejabberd
    container_name: ejabberd
    user: root
#    network_mode: host
    ports:
      - 5222:5222
      - 5269:5269
      - 5280:5280
    volumes:
      - ./ejabberd/database/:/opt/ejabberd/database
      - ./ejabberd/logs/:/opt/ejabberd/logs/
      - ./ejabberd/conf/:/opt/ejabberd/conf
      - ./ejabberd/ssl/:/opt/ejabberd/ssl
    environment:
#       - ERLANG_NODE=localhost
       - XMPP_DOMAIN=it-top.pp.ua
       - EJABBERD_ADMINS=admin@it-top.pp.ua
       - EJABBERD_USERS=admin@it-top.pp.ua:123456
